### ISSUE TITLE
Support for code highlighting in githubCodeBlocks

### ISSUE THREAD

**Issue by vithar** [showdownjs/showdown#215]
Do you plan to add support for syntax highlighting in githubCodeBlocks?

Something like this:

if (options.highlight) {
  codeblock = options.highlight(codeblock, language) || codeblock;
}

I can send PR.

**Comment by tivie** [comment]
Check https://github.com/showdownjs/prettify-extension

**Comment by vithar** [comment]
I seen this. But I think highlighting hook in githubCodeBlocks.js (where we know exact code block and language) will be more effective than using regexp to process ALL output.

**Comment by vithar** [comment]
prettify works only in browser, but I want to highlight code in NodeJS.

**Comment by tivie** [comment]
@vithar What do you mean by highlighting code in NodeJS?!

**Comment by matatk** [comment]
I was hoping that it might be possible to have a showdown extension that puts all the required highlighting markup into the HTML, so only CSS, and no JavaScript, is required on the browser to render the highlighted code.

That's [how it works with Pandoc](http://pandoc.org/README.html#syntax-highlighting): when Pandoc converts the Markdown to HTML, it adds in the required HTML code for each token in the code, and the CSS highlights the tokens however the user would like.

Perhaps this is what @vithar is asking for?  I think it'd be great to have such a feature, too.

**Comment by vithar** [comment]
Thanks, this is exactly that I mean.

**Comment by tivie** [comment]
I'm not sure what kind of HTML wizardry pandoc does. However, Showdown already adds classes to code blocks pertaining the language used.

for instance, this block...

    ```javascript
    function foo() {
      var bar = 'bar';
      return bar;
    }
    ```

gets converted into the following HTML:

```html
<pre><code class="javascript language-javascript">function foo() {
  var bar = 'bar';
  return bar;
}</code></pre>
```

**Comment by matatk** [comment]
With the same input, Pandoc uses a syntax-highlighting library to produce the following HTML. The HTML is marked up in the way that [Pygments](http://pygments.org) would do so (but as Pandoc is written in Haskell, as opposed to Python, it uses an equivalent Haskell library to do this).

```html
<div class="sourceCode"><pre class="sourceCode javascript"><code class="sourceCode javascript"><span class="kw">function</span> <span class="at">foo</span>() <span class="op">{</span>
  <span class="kw">var</span> bar <span class="op">=</span> <span class="st">&#39;bar&#39;</span><span class="op">;</span>
    <span class="cf">return</span> bar<span class="op">;</span>
  <span class="op">}</span></code></pre></div>
```

Here's some of the CSS that goes with this HTML to actually perform the highlighting.  Any CSS that assumes Pigments 'hints' have been added to the HTML would work.

```css
. . .
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
. . .
```

I've been trying to find an equivalent in JavaScript but most seem to take the approach that showdown-prettify does, which is to run some JS to inject the extra 'highlighting hints' HTML markup at runtime in the browser.  There is a wrapper for Pygments itself, but ideally I'd like to find an all-JavaScript solution, to avoid extra dependencies.
