### ISSUE TITLE
YML metadata does not support objects/arrays in it

### ISSUE THREAD

**Issue by GreepTheSheep** [showdownjs/showdown#941]
I'm trying to get datas that have objects and arrays on it in a YML format, but it returns something wrong

### .md file:
```yml
description: Remove a track by its UID from your favorite tracks
route: /api/token/map/favorite/{mapUid}/remove
method: POST
parameters:
    path:
        - mapUid:
            type: string
            description: The UID of the map
            required: true
            default: ""
```

### Returned object:
Excepted:

```json
{
    "description": "Remove a track by its UID from your favorite tracks",
    "route": "/api/token/map/favorite/{mapUid}/remove",
    "method": "POST",
    "parameters": {
        "path": {
            "mapUid": {
                "type": "string",
                "description": "The UID of the map",
                "required": true,
                "default": ""
            }
        }
    }
}
```

Actual:

```json
{
"description": "Remove a track by its UID from your favorite tracks",
"route": "/api/token/map/favorite/{mapUid}/remove",
"method": "POST",
"parameters: path:     mapUid:         type: string         description: The UID of the map         required: true         default": "&quot;&quot;"
}
```
